version: '3'
services:
  classicpress:
    image: classicpress/classicpress
    ports:
      - 8080:80
    volumes:
      - ./classicpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=classicpress
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
    depends_on:
      - db
    networks:
      - classicpress-network
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=classicpress
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - classicpress-network
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - classicpress
    networks:
      - classicpress-network
networks:
  classicpress-network: